name: yaaseen
description: Yasin sura.

version: 2.2.1+14

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.5.3+2
  flutter_bloc: ^8.1.1
  share_plus: ^4.0.10+1
  audioplayers: ^1.0.1
  url_launcher: ^6.1.5
  flutter_svg: ^1.0.3
  in_app_review: ^2.0.4
  http: ^0.13.5
  firebase_core: ^1.22.0
  firebase_messaging: ^13.0.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.4.8
  flutter_local_notifications: ^11.0.0
  uuid: ^3.0.6
  package_info_plus: ^1.4.3+1
  audio_service: ^0.18.7
  just_audio: ^0.9.29
  firebase_database: ^9.1.6
  flutter_html: ^3.0.0-alpha.3
  firebase_analytics: ^9.3.8
  badges: ^2.0.3
  on_click: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.2.0


flutter:


  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/


  fonts:
    - family: Me-Quran
      fonts:
        - asset: assets/fonts/arabic/Me-Quran-Regular.ttf
    
    - family: Al-Qalam
      fonts:
        - asset: assets/fonts/arabic/al-qalam-kitab.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/arabic/Amiri-Bold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700


