
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  flutter_build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
        
    - run: flutter pub get

  # building_ios:
  #   name: Build Flutter (iOS)
  #   needs: [flutter_build]
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-java@v1
  #     with:
  #       java-version: "12.x"
  #   - uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: '3.0.5'
  #       channel: 'stable'
  #   - run: flutter pub get
  #   - run: flutter clean
  #   - run: flutter build ios